exercises = {

"corvb_test_swipe": {"strokes": [[[0.6, 0.4], [0.6, 0.5], [0.6, 0.6]], [[0.5, 0.4], [0.5, 0.5], [0.5, 0.6]], [[0.4, 0.4], [0.4, 0.5], [0.4, 0.6]]],
         	           "accuracy_mult": 1,
	                   "length_mult": 1,
                     "speed_mult": 1,
                     "endpoint_mult": 1,
                     "point_value": 500,
	                   "author": "CorvBlimey",
                     "title": "Li'l Swipes",
	                   "description": "A simple vertical stroke series"},
 "corvb_long_swipe": {"strokes": [[[0.3, 0.3], [0.5, 0.3], [0.7, 0.3]], [[0.3, 0.4], [0.5, 0.4], [0.7, 0.4]], [[0.3, 0.5], [0.5, 0.5], [0.7, 0.5]],
                                  [[0.3, 0.6], [0.5, 0.6], [0.7, 0.6]], [[0.3, 0.7], [0.5, 0.7], [0.7, 0.7]]],
          	          "accuracy_mult": 1,
 	                    "length_mult": 1,
                      "speed_mult": 1,
                      "endpoint_mult": 1,
                      "point_value": 1000,
 	                    "author": "CorvBlimey",
                      "title": "Horizontal Strokes",
 	                    "description": "Stacked strokes, all the same length"},
"corvb_cross_lines": {"strokes": [[[0.3, 0.3], [0.7, 0.7]], [[0.8, 0.8], [0.75, 0.65]], [[0.1, 0.2], [0.5, 0.4]],
                                  [[0.5, 0.6], [0.5, 0.63]], [[0.7, 0.4], [0.7, 0.2]], [[0.4, 0.4], [0.2, 0.3]]],
         	            "accuracy_mult": 1,
	                    "length_mult": 1,
                      "speed_mult": 1,
                      "endpoint_mult": 1,
                      "point_value": 1500,
	                    "author": "CorvBlimey",
                      "title": "Diagonal Scratch",
	                    "description": "Diagonal lines of varying length and direction"}
};
